### ISSUE TITLE
rebooting during backup

### ISSUE THREAD

**Issue by ju5t3nc4s3** [archandanime/wz_flash-helper#9]
v3 only reboots during backup using v0.6.1_t31.zip

**Comment by gtxaspec** [comment]
If you pull the SD card, and place it back in your computer, inside the `wz_flash-helper` folder there should be some log files, could you attach them here?

**Comment by ju5t3nc4s3** [comment]
not getting a log.  reformated sd and tryed again and keeps rebooting. i do get a log using wz_mini_hacks

**Comment by ju5t3nc4s3** [comment]
is this just using DD to back up each partition?

**Comment by ju5t3nc4s3** [comment]
used wcv3_flash-helper to backup and worked fine

**Comment by archandanime** [comment]
Did you turn off `dry_run` option on `general.conf` file?

**Comment by ju5t3nc4s3** [comment]
yes tryed with yes and no.  both keep rebooting

**Comment by archandanime** [comment]
Could you share the `initramfs.log` and `initramfs_serial.log` inside `wz_flash-helper` directory on SD card?

**Comment by ju5t3nc4s3** [comment]
it didnt create a log during the wz_flasher.   so i used the wzv3_flasher to get backup

**Comment by archandanime** [comment]
Hmm did you hear the audio play when the you boots up the camera after extracting the installation file on SD card?

**Comment by ju5t3nc4s3** [comment]
[wcv3_flash-helper.log](https://github.com/archandanime/wz_flash-helper/files/13317268/wcv3_flash-helper.log)
 here is the log from wzv3

**Comment by ju5t3nc4s3** [comment]
it didnt even boot. the red light was only on for second . no audio nothen

**Comment by archandanime** [comment]
Hmm could you check again if your SD card was formatted as MBR instead of GPT?

**Comment by ju5t3nc4s3** [comment]
it was formatted correctly, even did it twice to make sure

**Comment by ju5t3nc4s3** [comment]
like stated the wzv3_flash-helper worked fine.  seems to be the boot file in wz_flash-helper

**Comment by gtxaspec** [comment]
just to confirm, 

did you use 
`v0.6.1_t20.zip`
or
`v0.6.1_t31.zip`

trying to debug what could be wrong.

thanks!

**Comment by ju5t3nc4s3** [comment]
t31 for wyze v3

**Comment by ju5t3nc4s3** [comment]
[factory_t31.tar.gz](https://github.com/archandanime/wz_flash-helper/files/13317388/factory_t31.tar.gz)

**Comment by archandanime** [comment]
Somehow the file `NOT_WORKING_factory_t31_ZMC6tiIDQN` has different hash from one on the release page:
```bash
> wget -q https://github.com/archandanime/wz_flash-helper/releases/download/v0.6.1/v0.6.1_t31.zip && unzip v0.6.1_t31.zip >/dev/null && md5sum factory_t31_ZMC6tiIDQN 
b62e92c7e3b8aec3caa7b3087ced236d  factory_t31_ZMC6tiIDQN
> md5sum NOT_WORKING_factory_t31_ZMC6tiIDQN 
14789aaf5ec4c37fb0293bb299701382  NOT_WORKING_factory_t31_ZMC6tiIDQN
```
Would you mind re-downloading the program?

**Comment by ju5t3nc4s3** [comment]
i did get different also  ..   crazy  new b62e92c7e3b8aec3caa7b3087ced236d

**Comment by archandanime** [comment]
Hope it works this time!

**Comment by ju5t3nc4s3** [comment]
im gona try to use it to flash openipc

**Comment by archandanime** [comment]
Hold on

**Comment by archandanime** [comment]
At the moment, after flashing OpenIPC, you won't be able to switch back to stock. OpenIPC does not allow booting using SD card kernel yet until [this Pull Request](https://github.com/OpenIPC/u-boot-ingenic/pull/3) is merged

**Comment by ju5t3nc4s3** [comment]
as long as i have the back up im good. dont have to boot with sd kernal. i have uart access if needed

**Comment by archandanime** [comment]
@ju5t3nc4s3

**Comment by archandanime** [comment]
That's good! Is your camera `t31x`?

**Comment by ju5t3nc4s3** [comment]
yes its t31x   have many others also

**Comment by ju5t3nc4s3** [comment]
have one that is a t31zx and cant even get uart anymore, tryed the cloner tool from openipc to flash the nor with no luck

**Comment by archandanime** [comment]
@gtxaspec has OpenIPC `uboot` for `t31x` with the ability to boot from SD card, you can use this one for now till the mentioned PR is merged.
[openipc_t31x_boot.zip](https://github.com/archandanime/wz_flash-helper/files/13317583/openipc_t31x_boot.zip)
It also works with `t31zl` and `t31zx`

**Comment by ju5t3nc4s3** [comment]
is boot partition mtdblock0 ?

**Comment by archandanime** [comment]
Yes, `boot` is uboot bootloader partition at `/dev/mtdblock0`.

**Comment by ju5t3nc4s3** [comment]
b62e92c7e3b8aec3caa7b3087ced236d  /media/ju5t3nc4s3/9AFA-2BF4/factory_t31_ZMC6tiIDQN

still rebooting

**Comment by archandanime** [comment]
Are you having a serial connection the camera? If so, disconnect both USB serial adapter and power cord for a few seconds then plug them back. USB serial adapter first then power cord.
uboot `Card did not respond to voltage select!` can be the issue.

**Comment by ju5t3nc4s3** [comment]
nothen but power on this one

**Comment by archandanime** [comment]
One more question, are you on stock or OpenIPC?

**Comment by ju5t3nc4s3** [comment]
stock

**Comment by archandanime** [comment]
I couldn't think of any reason why it doesn't work, would you mind using serial connection and sharing the boot log?

**Comment by ju5t3nc4s3** [comment]
this one is not opened yet, im trying one other thing first

**Comment by archandanime** [comment]
Take your time! Tell me if you need help.

**Comment by ju5t3nc4s3** [comment]
thaught it might be the rtsp firmware flashed to 4.36.9.139  and still doing the same. but the wzv3_flash-helper  works fine.

**Comment by ju5t3nc4s3** [comment]
might be bit . have to open add some header pins and find my ftdi

**Comment by ju5t3nc4s3** [comment]
@archandanime   will the network not connect if it set as hidden ssid. the oem wyze firmware will connect to hidden

**Comment by archandanime** [comment]
I'm not sure, I have not tried that yet

**Comment by archandanime** [comment]
@ju5t3nc4s3 not all characters are allowed for Wi-Fi password, it might be the reason

**Comment by archandanime** [comment]
@ju5t3nc4s3 latest release fixed the limitations with allowed characters for Wi-Fi password. Now all special characters are allowed, except for single quote(')
